### ISSUE TITLE
View Button Code Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#19]
When I click on View Button Code this is what I get lodged in the top, left corner of the screen...

![image](https://cloud.githubusercontent.com/assets/629241/8407629/607cad74-1e2e-11e5-82c5-32193a043784.png)

That's not very pretty and it's not very user friendly.  I'd like to display this in a lightbox, or at least center the window so it looks nice and is large enough for the code to be displayed.

I would also like to use some sort of syntax highlighter so the button is formatted nicely and is easy to read.

If possible, within the code we could highlight the insecure portions (pricing / email address).

**Comment by angelleye** [comment]
I would also like to display the actual button itself on the report row for the button.  We can do that, right?  

So then on the row you could see exactly which button it is, and then you could also click the button to view the code.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with the fancybox and syntaxhighliter code . and pushed latest code to Development branch for a review please review it when you get a chance and let me know your thoughts for the same.

**Comment by nishitlangaliya** [comment]
""I would also like to display the actual button itself on the report row for the button. We can do that, right?

So then on the row you could see exactly which button it is, and then you could also click the button to view the code."""

For this I understood your concern for display button. here what i thinking is user might have
form with many options , so that could make our row big so here i have one idea to display actual button.
1. we can have other view button link column like view button code . and then we can display actual button in fancybox.

please let me know your thoughts.

**Comment by angelleye** [comment]
Yes, I like that idea.  Or maybe instead of 2 separate view buttons we can put both the actual button display and the HTML code snippet on a single lightbox window..??

**Comment by nishitlangaliya** [comment]
Hi Andrew ,

I have added the actual button to fancybox below the html snippet and pushed latest code to "Development" branch for a review. please review it and let me know your thoughts for the same.

![screenshot-bmw dev2 in 2015-07-06 11-46-40](https://cloud.githubusercontent.com/assets/11435772/8516860/6d994b80-23d7-11e5-970c-20b62105b8cd.png)

**Comment by angelleye** [comment]
In Chrome I'm not getting the X at the top, right of the lightbox to close the window.  I can still close it just by clicking outside of it, but some people get confused by that and think they're stuck if they don't see the X.

**Comment by nishitlangaliya** [comment]
Done, Latest code pushed to Development branch for a review.
