### ISSUE TITLE
Scan Progress Bar

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#4]
Right now the only way I can tell if anything is happening when clicking the Scan button is by looking at the browser tab / status bar.  This will confuse users.

We need to add a progress bar of some sort so people can see that the scanner is indeed working, and try to provide a general idea of how much has been scanned vs. how much there is left to scan.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have Implemented jQuery progress bar for on click ' Scan Now' Button. I am attaching the screenshot of a progress bar functionality. 
Note : percentage showing in a progressbar will not be accurate and will not show base on scan done . because the percentage showing in the progressbar is based on settime out funcition in jquery. We have handled the complete progress event based on our scanning response. 

please see the attached screenshot and give me your thoughts and suggestions for the user interface view and text messages that are currently in screenshot .

![issue-4](https://cloud.githubusercontent.com/assets/11435772/7276969/ddf88392-e92a-11e4-9d48-eaadff332e60.png)

I have pushed the code into issue-4 once you confirm I will push it to development branch as well.

**Comment by nishitlangaliya** [comment]
latest code for pushed to development branch.

**Comment by angelleye** [comment]
I'm going to close this issue because this is good enough to launch with, but I still think we should be able to improve upon this.  I'll create a new issue for the 1.1 update.
